#!/bin/bash
#SBATCH --job-name=gin_sweep
#SBATCH --array=0-29
#SBATCH -o /scratch/mk8737/rl_pretrain/tmp_slurm_%A_%a.out
#SBATCH -e /scratch/mk8737/rl_pretrain/tmp_slurm_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32gb
#SBATCH --time=3-00:00:00

module purge
module load cuda/11.8.0

# Make sure Conda is initialised for non-interactive shells
source /share/apps/NYUAD5/miniconda/3-4.11.0/bin/activate
conda activate rl_pretrain
PROJECT_ROOT="/scratch/mk8737/rl_pretrain"
cd $PROJECT_ROOT

# Copy outputs into designated directory
LOG_DIR_NAME="GIN_sag" # all gin are trained with dataloader
RESULTS_DIR=$RL_PRETRAIN_SCRATCH/sweep_results/${LOG_DIR_NAME}_${SLURM_ARRAY_JOB_ID}
mkdir -p $RESULTS_DIR

# # Get the absolute path of the directory where the script is located
# SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# # Load environment variables from .env file if it exists
# ENV_FILE="$SCRIPT_DIR/../.env"
# if [ -f "$ENV_FILE" ]; then
#     echo "Loading environment variables from $ENV_FILE"
#     source "$ENV_FILE"
# fi

export WANDB_API_KEY="REDACTED"
# Check for WANDB_API_KEY
if [ -z "$WANDB_API_KEY" ]; then
  echo "Error: WANDB_API_KEY is not set. Please set it before running the script."
  exit 1
fi

# Export your W&B entity and project name
export WANDB_ENTITY="mk8737-new-york-university" # IMPORTANT: Update with your W&B entity
export WANDB_PROJECT="rl_pretrain_hp_sweeps" # IMPORTANT: Update with your W&B project

# The sweep ID will be generated by the first agent and stored in a file.
SWEEP_ID_FILE="playground/sweep_id.txt"
rm -f $SWEEP_ID_FILE


# Agent 1 creates the sweep and saves the ID.
if [ $SLURM_ARRAY_TASK_ID -eq 0 ]; then
    
    echo "Creating sweep..."
    # Create sweep and capture the sweep ID from the output
    # The `2>&1` redirects stderr to stdout, so that grep can capture the ID
    # SWEEP_ID=$(wandb sweep playground/sweep.yaml --project $WANDB_PROJECT 2>&1 | grep "Creating sweep with ID:" | awk '{print $6}')
    # SWEEP_ID=$(wandb sweep playground/sweep.yaml --project $WANDB_PROJECT 2>&1 | sed 's/\x1B\[[0-9;]*[JKmsu]//g' | grep "Creating sweep with ID:" | awk '{print $6}')
    # SWEEP_INFO=$(wandb sweep --format json playground/sweep.yaml --project $WANDB_PROJECT)
    # Extract sweep ID from JSON
    # SWEEP_ID=$(echo "$SWEEP_INFO" | jq -r '.sweep_id')

    echo "foo1"

    # SWEEP_ID=$(python playground/retrieve_sweep_id.py 2>&1 | grep "Create sweep with ID:" | awk '{print $5}')
    SWEEP_ID=$(python playground/retrieve_sweep_id.py) #!!!IMPORTANT: Make sure this script creates a sweep with the correct config file
    echo $SWEEP_ID

    if [ -z "$SWEEP_ID" ]; then
        echo "Failed to create sweep or capture Sweep ID. Exiting."
        exit 1
    fi

    echo $SWEEP_ID > $SWEEP_ID_FILE
    echo "Sweep created with ID: $SWEEP_ID"
else
    # Other agents wait for the sweep ID file to be created.
    echo "Waiting for sweep ID..."
    while [ ! -f $SWEEP_ID_FILE ]; do
        sleep 5
    done
    SWEEP_ID=$(cat $SWEEP_ID_FILE)
    echo "Found Sweep ID: $SWEEP_ID"
fi

# All agents run the sweep with the same ID.
# The --count parameter tells the agent how many runs to try before exiting.
echo "Starting wandb agent for sweep $SWEEP_ID..."
wandb agent --count 1 ${WANDB_ENTITY}/${WANDB_PROJECT}/${SWEEP_ID}
# wandb agent --count 1 ${SWEEP_ID}

echo "Agent finished."

mv /scratch/mk8737/rl_pretrain/tmp_slurm_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out $RESULTS_DIR/job_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out
mv /scratch/mk8737/rl_pretrain/tmp_slurm_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err $RESULTS_DIR/job_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err